// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1RSYSegiwrzaKVX4F2vE7IbTTLYSjSaQ',
    appId: '1:177939459234:web:48b51a46be33da23f73bfb',
    messagingSenderId: '177939459234',
    projectId: 'firebase-entegrasyonn2',
    authDomain: 'fir-entegrasyonn2.firebaseapp.com',
    storageBucket: 'firebase-entegrasyonn2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb6WZFvwCh7gNMsa9hw6ey3bsfmVvtsaM',
    appId: '1:177939459234:android:1a30528230add41ff73bfb',
    messagingSenderId: '177939459234',
    projectId: 'firebase-entegrasyonn2',
    storageBucket: 'firebase-entegrasyonn2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUssfPyGgyFLWo4Z7U5Dqx24mw-cJ1WVg',
    appId: '1:177939459234:ios:2e54dcd60470c82ef73bfb',
    messagingSenderId: '177939459234',
    projectId: 'firebase-entegrasyonn2',
    storageBucket: 'firebase-entegrasyonn2.appspot.com',
    iosClientId: '177939459234-31i3h2n25s8l83fkc19a0anvid4q717s.apps.googleusercontent.com',
    iosBundleId: 'com.dh.firestoreproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUssfPyGgyFLWo4Z7U5Dqx24mw-cJ1WVg',
    appId: '1:177939459234:ios:2e54dcd60470c82ef73bfb',
    messagingSenderId: '177939459234',
    projectId: 'firebase-entegrasyonn2',
    storageBucket: 'firebase-entegrasyonn2.appspot.com',
    iosClientId: '177939459234-31i3h2n25s8l83fkc19a0anvid4q717s.apps.googleusercontent.com',
    iosBundleId: 'com.dh.firestoreproject',
  );
}
